project:
  type: website
  output-dir: docs
  resources:
    - "00-Angel-Feliz-Resume.pdf"
    - CNAME

website:
  title: "Angel Feliz"
  site-url: https://angelfeliz.com
  description: "Personal blog related to R and Data Science"
  open-graph:
    locale: en_US
  comments:
    utterances:
      repo: AngelFelizR/myblog
  navbar:
    left:
      - href: posts.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/AngelFelizR/
      - icon: linkedin
        href: https://do.linkedin.com/in/angel-esteban-feliz-ferreras

format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css   
   
editor: source
