project:
  type: website
  output-dir: docs

website:
  title: "Angel Feliz"
  navbar:
    left:
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: Blog
      - icon: github
        href: https://github.com/AngelFelizR/
      - icon: twitter
        href: https://twitter.com/angel_feliz_f
      - icon: linkedin
        href: https://do.linkedin.com/in/angel-esteban-feliz-ferreras
      
format:
  html:
    theme: cosmo
    css: styles.css

editor: source

resources:
  - CNAME
