name: Render and Deploy Report

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/angelfelizr/personal-blog:4.5.3
      options: --user root

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # This ensures code is in the standard path the job expects
          path: personal_blog

      - name: Run Pipeline and Render
        # We set the working directory to match your manual 'cd' step
        working-directory: ./personal_blog
        run: |
          nix-shell --run "quarto render"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Path relative to the workspace root
          publish_dir: ./personal_blog/docs
          publish_branch: gh-pages
  
